### ISSUE TITLE
RuntimeError: eventmachine not initialized: evma_connect_to_server

### ISSUE THREAD

**Issue by gabrieltong** [mloughran/em-hiredis#43]
Hey I'm a new guy to `em-hiredis`, so I don't know much.
my steps are
1. add to gemfile `gem 'em-hiredis'`, and `bundle install`
2. in my some method, I run
```
require 'em-hiredis'
redis = EM::Hiredis.connect
```
the second will raise this error

**Comment by Litchiware** [comment]
You can run your codes this way:

```ruby
require 'em-hiredis'
EM.run {
  redis = EM::Hiredis.connect
  ...
}
```
